config/routes.rb
Rails.application.routes.draw do
  resources :attachments

  resources :posts

  devise_for :usuarios, :controllers => { :omniauth_callbacks => "omniauth_callbacks"}

  resources :usuario

   root 'welcome#index'

  post "usuario/follow"

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :post

  include Picturable
end

app/models/concerns/picturable.rb
module Picturable
  extend ActiveSupport::Concern
  included  do
    after_save :guardar_archivo
  end

  if self.respond_to?(:post_id)
    PATH_ARCHIVOS = File.join Rails.root, "public", "archivos", "attachments"
  else
    PATH_ARCHIVOS = File.join Rails.root, "public", "archivos", "posts"
  end

  def archivo=(archivo)
    unless archivo.blank?
      @archivo = archivo
      if self.respond_to?(:nombre)
        self.nombre = @archivo.original_filename
      end

      self.extension = @archivo.original_filename.split(".").last.downcase
    end
  end

  def path_imagen
    File.join PATH_ARCHIVOS, "#{self.id}.#{self.extension}"
  end

  def tiene_archivo?
    File.exist? PATH_ARCHIVOS
  end

  private
  def guardar_archivo
    if @archivo
      FileUtils.mkdir_p PATH_ARCHIVOS
      File.open(path_imagen,"wb") do |f|
        f.write(@archivo.read)
      end
      @archivo = nil
    end
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :friend, class_name: "Usuario"

  include PublicActivity::Model
  tracked owner: Proc.new { |controller,model| controller.current_usuario }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :usuario
  has_many :attachments
  validates :titulo, presence: true, uniqueness: true

  include Picturable
  include PublicActivity::Model
  tracked owner: Proc.new { |controller,model| controller.current_usuario }
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :posts
  has_many :friendships, foreign_key: "usuario_id", dependent: :destroy

  has_many :follows, through: :friendships, source: :friend

  has_many :followers_friendships, class_name: "Friendship", foreign_key: "friend_id"

  has_many :followers, through: :followers_friendships, source: :usuario

  def follows!(amigo_id)
    self.friendships.create!(friend_id: amigo_id)
  end

  def can_follow?(amigo_id)
    not amigo_id == self.id or friendships.where(friend_id: amigo_id).size > 0
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |usuario|
      usuario.provider = auth.provider
      usuario.uid = auth.uid
      usuario.email = auth.info.email
      usuario.password = Devise.friendly_token[0,20]
      usuario.nombre = auth.info.first_name
      usuario.apellido = auth.info.last_name
      usuario.username = auth.info.nickname
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include PublicActivity::StoreController
  protect_from_forgery with: :exception
  #before_action :authenticate_usuario! #el usuario tendra acceso solo si esta logeado

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:nombre, :apellido, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
          |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
          |u| u.permit(registration_params)
      }
    end
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @attachments = Attachment.all
    respond_with(@attachments)
  end

  def show
    respond_with(@attachment)
  end

  def new
    @attachment = Attachment.new
    respond_with(@attachment)
  end

  def edit
  end

  def create
    @attachment = Attachment.new(attachment_params)
    @attachment.save
    respond_with(@attachment)
  end

  def update
    @attachment.update(attachment_params)
    respond_with(@attachment)
  end

  def destroy
    @attachment.destroy
    respond_with(@attachment)
  end

  private
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    def attachment_params
      params.require(:attachment).permit(:nombre, :extension, :post_id, :archivo)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @usuario = Usuario.from_omniauth(request.env["omniauth.auth"])

    if @usuario.persisted? #Validacion de creacion de Usuario
      sign_in_and_redirect @usuario
    else
      redirect_to new_usuario_registration_url # redireccion para la vista de registro para corregir errores
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:show, :index]

  respond_to :html, :json

  def index
    @posts = Post.all
    respond_with(@posts)
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = current_usuario.posts.new(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:titulo, :contenido, :archivo)
    end
end

app/controllers/usuario_controller.rb
class UsuarioController < ApplicationController

  def show
    @usuario = Usuario.find(params[:id])
  end
  def follow
    respond_to do |format|
      if current_usuario.follows!(post_params[:friend_id])
        format.json {head :no_content}
      else

        format.json {render json: post_params}
      end
    end
  end

  private
  def post_params
    params.require(:usuario).permit(:friend_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @actividades = PublicActivity::Activity.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_email_oauth #helper para autocompletar los datos por registro en omniauth
    if devise_error_messages!
      @usuario.email
    else

    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attachments/_form.html.erb
<%= form_for(@attachment) do |f| %>
    <% if @attachment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

          <ul>
            <% @attachment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :archivo %><br>
      <%= f.file_field :archivo %>
    </div>

    <div class="field">
      <%= f.label :post_id, "Post" %>
      <%= f.collection_select :post_id, Post.all, :id, :titulo %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<h1>Listing attachments</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Extension</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.nombre %></td>
        <td><%= attachment.extension %></td>
        <td><%= attachment.post %></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @attachment.nombre %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @attachment.extension %>
</p>

<p>
  <strong>Post:</strong>
  <%= @attachment.post %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Compra de archivos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<header>
  <nav>
    <ul class="nav nav-tabs">
      <li>
        <%= link_to "Inicio", root_path %>
      </li>
      <li>
        <%= link_to "Posts", posts_path %>
      </li>
      <% if usuario_signed_in? %>
          <li>
            <%= link_to "Editar_Perfil", edit_usuario_registration_path(current_usuario) %>
          </li>
          <li>
            <%= link_to "Cerrar Sesion", destroy_usuario_session_path, method: :delete%>
          </li>
          <li>
            <%= link_to "Mi Perfil", current_usuario %>
          </li>
      <% else %>
          <li>
            <%=  link_to "Ingresar", new_usuario_session_path %>
          </li>
          <li>
            <%= link_to "Registrarse", new_usuario_registration_path %>
          </li>

      <% end %>

    </ul>

  </nav>

</header>

<p class="notice" style="<%= "display:none;" if notice.nil? %>"><%= notice %></p>
<p class="alert" style="<%= "display:none;" if alert.nil? %>"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :archivo %><br>
    <%= f.file_field :archivo, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Subir Post", class: "btn btn-info" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th>Extension</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.titulo %></td>
        <td><%= post.contenido %></td>
        <td><%= post.extension %></td>
        <td><%= post.usuario %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>Nuevo Post</h1>
<div class="container">
  <div class="row">
    <div class="col-md5 center-block">
      <%= render 'form' %>

      <%= link_to 'Back', posts_path %>

    </div>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @post.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @post.contenido %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @post.extension %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @post.usuario %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/public_activity/friendship/_create.html.erb
<li class="list-group-item">
  <%= link_to activity.owner.nombre+ " " + activity.owner.apellido, activity.owner %> se hizo amigo de:
  <%= link_to activity.trackable.friend.nombre+ " "+ activity.trackable.friend.apellido, activity.trackable.friend %>
</li>

app/views/public_activity/post/_create.html.erb
<li class="list-group-item">
  <%= link_to activity.owner.nombre+ " " + activity.owner.apellido, activity.owner %> ha creado un Post:
  <%= link_to activity.trackable.titulo, activity.trackable %>
</li>

app/views/public_activity/post/_update.html.erb
<li class="list-group-item">
  <%= link_to activity.owner.nombre+ " " + activity.owner.apellido, activity.owner %> ha actualizado un Post:
  <%= link_to activity.trackable.titulo, activity.trackable %>
</li>

app/views/usuario/show.html.erb
<h1><%= @usuario.nombre + " " + @usuario.apellido %></h1>

<% if usuario_signed_in? and current_usuario.can_follow?(@usuario.id) %>
    <button class="btn btn-info" id="follw_btn" data-friend="<%= @usuario.id %>" ><i class="fa fa-user-plus"></i> Follow</button>
<% end %>

app/views/welcome/index.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 center-block no-float">

      <h1>Bienvenido :)</h1>

      <ul class="list-group">
        <%=  render_activities(@actividades) %>
      </ul>

    </div>
  </div>
</div>